services:
  - type: web
    name: face-attendance-backend
    env: docker
    plan: starter
    region: singapore
    scaling:
      minInstances: 1
      maxInstances: 3
    resources:
      cpu: 1.0
      memory: 2GB
    envVars:
      - key: S3_BUCKET
        value: mobilefacenet
      - key: AWS_DEFAULT_REGION
        value: ap-south-1
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /app
      - key: PORT
        value: "8000"
    healthCheckPath: /
    autoDeploy: true
